---
title: "Lab_1"
author: "Kanke Sergey"
date: '8 октября 2018 г '
output: html_document
---

```{r}
#Задание 1
#Сгенерируйте 200 случайных значений из стандартного экспоненциального распределения и сохраните в вектор exp.1. Найдите среднее и стандартное отклонение из данных этого вектора.
exp.1<-rexp(n = 200)
m.1<-mean(exp.1)
s.1<-sd(exp.1)
#среднее отклонение
m.1
#стандартное отклонение
s.1
#Повторите, использовав следующие значения параметра rate: 0.1, 0.5, 5, 10, и сохраните результаты в векторы: exp.0.1, exp.0.5, exp.5, exp.10.
#rate = 0.1
exp.0.1<-rexp(n = 200, rate = 0.1)
m.0.1<-mean(exp.0.1)
s.0.1<-sd(exp.0.1)
#среднее
m.0.1
#стандартное отклонение
s.0.1
#rate = 0.5
exp.0.5<-rexp(n = 200, rate = 0.5)
m.0.5<-mean(exp.0.5)
s.0.5<-sd(exp.0.5)
#среднее
m.0.5
#стандартное отклонение
s.0.5
#rate = 5
exp.5<-rexp(n = 200, rate = 5)
m.5<-mean(exp.5)
s.5<-sd(exp.5)
#среднее
m.5
#стандартное отклонение
s.5
#rate = 10
exp.10<-rexp(n = 200, rate = 10)
m.10<-mean(exp.10)
s.10<-sd(exp.10)
#среднее
m.10
#стандартное отклонение
s.10
#Используйте функцию hist() для построения гистограммы полученного ранее стандартного распределения.
hist(exp.1, prob = TRUE)
#Используйте функцию plot() с тем же самым вектором для построения графика значений в порядке следования.
plot(exp.1)
#Используйте функцию plot() с любыми двумя полученными ранее векторами, чтобы получить диаграмму рассеяния (scatterplot) этих векторов относительно друг друга.
plot(exp.0.1, exp.10)
#Теперь сравним свойства всех наших векторов. Для начала создадим вектор, содержащий средние значения каждого из 5 полученных ранее распределений в порядке их создания. Полученный вектор сохраним в переменную exp.means.
#вектор ср.знач
exp.m<-c(m.1, m.0.1, m.0.5, m.5, m.10)
#вектор ст.откл
exp.s<-c(s.1, s.0.1, s.0.5, s.5, s.10)
#Вектор с пятью средними относительно каждого из пяти векторов с различными значениями rate.
exp.m.repeat <- rep(exp.m, each = 40)
pairs(~exp.m.repeat + exp.1 + exp.0.1 + exp.0.5 + exp.5 + exp.10)
#Вектор с пятью стандартными отклонениями относительно каждого из пяти векторов с различными значениями rate.
exp.s.repeat <- rep(exp.s, each = 40);
pairs(~exp.s.repeat + exp.1 + exp.0.1 + exp.0.5 + exp.5 + exp.10)
#Вектор с пятью средними относительно вектора с пятью стандартными отклонениями.
plot(exp.m, exp.s)
lines(exp.m,exp.s)
#Линейная зависимость
```

```{r}
#Задание 2
#Для демонстрации сгенерируйте 1100000 (1 млн. 100 тысяч) чисел из стандартного экспоненциального распределения и сохраните их в вектор huge.exp.1. Получите среднее и стандартное отклонение.
huge.exp.1<-rexp(n=1100000)
huge.m.1<-mean(huge.exp.1)
huge.m.1
huge.s.1<-sd(huge.exp.1)
huge.s.1
#Получите гистограмму huge.exp.1. Она соответствует функции 1 - e:^(-x)? Должна ли?
hist(huge.exp.1, prob = TRUE)
curve(1 - exp(-x), add = TRUE, col = "blue")
#Гистограмма не соответствует функции распределения 1 - e^(-x), так как это гистограмма  функции плотности распределения x*e^(-x)
#Получите среднее всех чисел из huge.exp.1 строго больших 1. Для проверки выборки может потребоваться новый вектор.
vec.big<-c(huge.exp.1[huge.exp.1>1])
mean.big<-mean(vec.big)
mean.big
#Получите матрицу huge.exp.1.mat, содержащую 1100 строк и 1000 колонок. Постройте гистограмму, использовав полученную матрицу. Что можно сказать о полученных данных?
huge.exp.1.mat<-matrix(data = huge.exp.1, nrow = 1100, ncol = 1000)
hist(huge.exp.1.mat, prob = TRUE)
#Рассчитайте среднее 137-й колонки из huge.exp.1.mat.
mean.137<-mean(huge.exp.1.mat[,137])
mean.137
#Найдите среднее всей 1000 колонок и сохраните их в вектор. Отобразите диаграмму средних зннчений колонок. Объясните почему форма диаграммы отличается от виденных ранее.
mean.1000<-c(colMeans(huge.exp.1.mat))
mean.1000
hist(mean.1000, prob = TRUE)
#Рассчитайте квадрат каждого значения из huge.exp.1 и найдите среднее и стандартное отклонение полученного вектора квадратов. Объясните отличие от соответствующих показателей вектора huge.exp.1. Вам может помочь формула, по которой R рассчитывает стандартное отклонение: sqrt(sum((x - mean(x))^2) / (n - 1)).
quadro<-c(huge.exp.1^2)
huge.m.quadro<-mean(quadro)
huge.s.quadro<-sqrt(var(quadro))
#Чем больше х, тем больше значения среднего и стандартного отклонения так как  х в числителе 
```