---
title: "LAB_3"
author: "Kanke Sergey"
date: '11 октября 2018 г '
output: html_document
---
```{r}
#Задание 1
#1 Используйте команду readLines для загрузки файла в текстовый вектор html.
html <- readLines("forbes.htm")
#a Сколько строк в файле?
length.1 <- length(html)
#b Сколько символов в файле?
count.char <- sum(nchar(html))
#2 Откройте файл в текстовом редакторе. Найдите строки, содержащие данные о Билле Гейтсе:($72 B) и Ларри Эллисоне: ($41 B) и запомните размер их дохода.
#3 Напишите шаблон регулярного выражения и используйте функцию grep, чтобы извлечь размер дохода из данных в векторе html. Удостоверьтесь, что полученный вектор номеров строк содержит содержит ровно 100 записей и ссылается на номера строк в котрых действительно есть информация о доходе, а не просто первый попавшийся текст.
my.pattern <- "\\$+\\d+\\,?\\d? B"
my.grep <- grep(my.pattern, html)
html[my.grep[1]]
#Напишите код, использовав регулярное выражение из п. 3, и функции regexp и regmatches, чтобы извлечь все данные о доходе. Проверьте следующее:
my.data <- c(regmatches(html,regexpr(my.pattern, html)))
#Должно быть ровно сто значений.
length(my.data)
#Самый большой доход должен быть доход Билла Гейтса
my.data[1] == "$72 B"
#Такой доход должен быть в списке один раз.
length(my.data[my.data == "$72 B"])
#В всписке должна быть цифра, которую мы запомнили для Ларри Эллисона.
any(my.data == "$41 B")
#Должно быть как минимум два значения, встречающихся несколько раз.
any(duplicated(my.data))
```

```{r}
#Задание 2
#В данных доход представлен в формате "$42 B", что означает 42 ?? 10^9. Преобразуйте этот формат в числовой и сохраните в вектор worths. Удостоверьтесь в следующем:
pattern.2<-"\\d+\\,?\\d?"
num <-c(regmatches(my.data,regexpr(pattern.2, my.data)))
worths<-c(as.numeric(gsub(",",".", num))*10^9)

#worths является вектором и в нём сто занчений типа double.
length(worths)
typeof(worths)
#Все элементы вектора worths больше 1 миллиарда.
all(worths > 10^9)
#Самое большое число это доход Билла Гейтса.
max(worths) == 72*10^9
#Используйте вектор worths , чтобы выяснить следующее:
#Какова медиана ста этих записей?
median(worths)
#Средний доход?
mean(worths)
#Как много людей из этого списка имеют доход больше 5млрд., 10, 25?
sum(worths[worths > 5*10^9])
sum(worths[worths > 10*10^9])
sum(worths[worths > 25*10^9])
#Какой их общий доход?
all.worths<-sum(worths)
all.worths
#Какую долю от общего дохода, составляет пятёрка самых богатых.
worths.5<-(sum(worths[1:5]))/all.worths
worths.5
#Какую долю от общего дохода, составляют 20 самых богатых.
worths.20<-(sum(worths[1:20]))/all.worths
worths.20
#В данных федерального резерва США найдите показатель дохода всех домохозяйств (Household net worth) в соответвующем году, какую долю общего дохода составляют 100 богатейших людей.
household.net.worth <- 83.280*10^9
worths.100<-all.worths/(household.net.worth + all.worths)
worths.100

```

